//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.10 at 02:16:56 PM GMT+06:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://smsc.kz/sys/soap.php")
package kz.kaps.resort.dataproviders.sms.soap.wsdl;
