//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.10 at 02:16:56 PM GMT+06:00 
//


package kz.kaps.resort.dataproviders.sms.soap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sendresult" type="{https://smsc.kz/sys/soap.php}SendResponseType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendresult"
})
@XmlRootElement(name = "SendResponse")
public class SendResponse {

    @XmlElement(required = true)
    protected SendResponseType sendresult;

    /**
     * Gets the value of the sendresult property.
     * 
     * @return
     *     possible object is
     *     {@link SendResponseType }
     *     
     */
    public SendResponseType getSendresult() {
        return sendresult;
    }

    /**
     * Sets the value of the sendresult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendResponseType }
     *     
     */
    public void setSendresult(SendResponseType value) {
        this.sendresult = value;
    }

}
